name: qb-amd64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - cross_host: aarch64-linux-musl
            openssl_compiler: linux-aarch64
            qt_device: linux-arm-generic-g++
          - cross_host: x86_64-linux-musl
            openssl_compiler: linux-x86_64
            qt_device: linux-generic-g++
    steps:
      - uses: actions/checkout@v2.3.4
      - run: apk add bash
        shell: ash {0}
      - run: bash qbittorrent-nox-static.sh
      - run: bash qbittorrent-nox-static.sh zlib
      - run: bash qbittorrent-nox-static.sh openssl
      # - run: bash qbittorrent-nox-static.sh icu
      - run: bash qbittorrent-nox-static.sh boost
      - run: bash qbittorrent-nox-static.sh libtorrent
      # - run: bash qbittorrent-nox-static.sh libtorrent -pr userdocs/qbittorrent-nox-static
      - run: bash qbittorrent-nox-static.sh qtbase
      # - run: bash qbittorrent-nox-static.sh qtbase -i
      - run: bash qbittorrent-nox-static.sh qttools
      - run: bash qbittorrent-nox-static.sh qbittorrent
      # - run: bash qbittorrent-nox-static.sh qbittorrent -pr userdocs/qbittorrent-nox-static
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.2.3
        with:
          name: qbittorrent-nox
          path: qb-build/completed/qbittorrent-nox
