name: swizzin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - run: apt update
      - run: apt upgrade
      - run: apt install curl
      - run: curl -sL git.io/swizzin --unattend nginx panel --user tester --pass test1234 | bash
      - run: systemctl restart panel

