name: swizzin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get -y upgrade
      - run: sudo apt-get -y install python git curl
      #
      - run: git clone  https://github.com/gdraheim/docker-systemctl-replacement.git
      - run: sudo cp -f docker-systemctl-replacement/files/docker/systemctl.py /usr/bin/systemctl
      #
      - run: curl -sL git.io/swizzin | sudo tty=$(readlink /proc/$$/fd/2) TERM=xterm bash -s - --unattend nginx panel --user username --pass password --skip-cracklib
      - run: sudo systemctl status panel
      - run: sudo systemctl start panel
      - run: sudo systemctl stop panel
      - run: sudo systemctl status nginx
      - run: sudo systemctl start nginx
      - run: sudo systemctl stop nginx
      
