name: qb-amd64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run --platform linux/arm64 -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/test/test":"/github/workspace" --rm -t arm64v8/alpine apk add bash && ls /github/workspace && bash /github/workspace/qbittorrent-nox-static.sh
      # - run: apk add bash
      # - run: bash qbittorrent-nox-static.sh
      #- run: bash qbittorrent-nox-static.sh zlib
      #- run: bash qbittorrent-nox-static.sh openssl
      #- run: bash qbittorrent-nox-static.sh icu
      #- run: bash qbittorrent-nox-static.sh boost
      #- run: bash qbittorrent-nox-static.sh libtorrent
      #- run: bash qbittorrent-nox-static.sh qtbase
      #- run: bash qbittorrent-nox-static.sh qtbase -i
      #- run: bash qbittorrent-nox-static.sh qttools
      #- run: bash qbittorrent-nox-static.sh qbittorrent
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: qbittorrent-nox
          path: qb-build/completed/qbittorrent-nox
